### ISSUE TITLE
AI Issues Epic

### ISSUE THREAD

**Issue by skeet70** [Duelers/Duelers#148]
- [ ] does not play cards as often as it should
- [ ] Cannot play spells (at all)
- [ ] ? Can use minion abilities that require targeting ?
- [ ] Provoke bug
- [ ] Turn doesn’t end sometimes when surrounded
