### ISSUE TITLE
P2P Issues Epic

### ISSUE THREAD

**Issue by skeet70** [Duelers/Duelers#149]
- [ ] if the person hosting the server does not have the account the client is using to try to log in with(e.g. host user does not have the john doe account in their file directory), weird stuff happens.
- [ ] If two users log in using the same account (e.g. john doe) the second person to log in will be told the account is already online but will not be kicked out.
- [ ] If the person hosting the server quits the game the server is closed for the other players currently connected
- [ ] game rules is based on the game version the host server is running on. if the host server is running a version where replace card feature isnt implemented, then players wouldnt be able to replace
- [ ] Reconnect to server does not properly
- [ ] Users have to edit configs to switch between local and p2p mode

**Comment by MaSer713** [comment]
I am crossing off the 3rd and 4th issues.
The 3rd one is fixed by decoupling (see https://github.com/Duelers/Duelers/tree/dedicated_serverr)
The 4th one does not seem like an issue

**Comment by fluffy-hamster** [comment]
Removing "Users have to edit configs to switch between local and p2p mode"  Because I do not think this is a problem we need to address right now

**Comment by fluffy-hamster** [comment]
@MaSer713  Is reconnection still outstanding or a solved issue?

**Comment by MaSer713** [comment]
Yep
