### ISSUE TITLE
Spectate Epic

### ISSUE THREAD

**Issue by skeet70** [Duelers/Duelers#164]
- [ ] basic implementation #160 
- [ ] Add both hands to display
- [ ] Add deck info (e.g cards in deck, maybe also timer info)
- [ ] When game is over, after some game over screen#

**Comment by fluffy-hamster** [comment]
be nice to have this for tourney

**Comment by fluffy-hamster** [comment]
![image](https://user-images.githubusercontent.com/25908852/76375612-277f5580-633e-11ea-9453-5d022fab0015.png)
