### ISSUE TITLE
Global Chat Epic

### ISSUE THREAD

**Issue by skeet70** [Duelers/Duelers#204]
- [ ] Lacks Test Wrapping
- [ ] Does not auto scroll
- [ ] Should be in corner in main screen as opposed to button !?
- [ ] Chat should be displayed while queueing !?
- [ ] Keyboard shortcut not working ?? Remove/Fix #104

**Comment by fluffy-hamster** [comment]
Im basically thinking we should have something a bit like WoW
