### ISSUE TITLE
UI Feedback Epic

### ISSUE THREAD

**Issue by skeet70** [Duelers/Duelers#211]
- [ ] make enemy minions look more distinct from own guys
- [ ] minions with shit to do should look different from exhausted minions
- [ ] turn timer /display enemy time (like shardbound)
- [ ] When Low on time, User should be warned (visual and audio cues)
- [ ] display number of enemy cards in hand/deck
- [ ] display deck size
- [ ] grey out cards you cant play #179 
- [ ] grey out replace when it cannot be used #153 
- [ ] large heath numbers are off centre
- [ ] display current available mana in numerical form (debateable)
- [ ] Make start of turn more obvious (sound/visual cues)
- [ ] add visual cues for effects (e.g provoke)

**Comment by skeet70** [comment]
#210 is sorta related.

**Comment by skeet70** [comment]
```
Chris Feb 26 at 3:17 AM (edited)
Made a start on handsize:
Add-HandSize-To-UI

This branch is broken. However, it act as an initial starting point should someone want to jump on this.
```

**Comment by fluffy-hamster** [comment]
![image](https://user-images.githubusercontent.com/25908852/77523831-4291af80-6e7e-11ea-8c82-f00535022db5.png)
