### ISSUE TITLE
Add 'Elo' ratings

### ISSUE THREAD

**Issue by fluffy-hamster** [Duelers/Duelers#258]
Some experimentation will have to be done regarding K values and even if Elo is the best formula (e.g Gieko might be better).  Moreover, we may also need to factor in p1 vs p2 advantage.

Anyway, this epic would consist of the following parts:

- [ ] Implement rating system of  ranked play (for now, let's match that global games).
- [ ] Add elo to 'online games' table
- [ ] Add elo to ingame profile
- [ ] Have some up-to-date list of top players (does not necessarily need to be in game)
- [ ] Documentation for players.
