### ISSUE TITLE
Add Basic Faction support

### ISSUE THREAD

**Issue by fluffy-hamster** [Duelers/Duelers#509]
- [x] Add factions to Json cards #512
- [ ] Add rudimentary faction support during deckbuilding #517
- [ ] Add faction to each card (e.g. use old gem rarity code to signify factions) #517
